openapi: 3.0.0
info:
  title: Wallet API
  description: API для управления кошельками, включая проверку баланса, пополнение и получение месячной статистики.
  version: 1.0.0
  contact:
    name: Jamshed Juraev
    email: jamshedjuraev95@gmail.com

paths:
  /v1/wallet/balance:
    post:
      summary: Get wallet balance
      description: Возвращает текущий баланс кошелька.
      operationId: GetWalletBalance
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  example: "user_account_12345"
      responses:
        '200':
          description: Баланс кошелька успешно получен.
          content:
            application/json:
              schema:
                type: object
                properties:
                  wallet_balance:
                    type: number
                    format: float
                    example: 1000.0
        '400':
          description: Неверные данные запроса.
        '404':
          description: Кошелек не найден.

  /v1/wallet/exists:
    post:
      summary: Check if wallet exists
      description: Проверяет, существует ли кошелек.
      operationId: CheckWalletExists
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  example: "user_account_12345"
      responses:
        '200':
          description: Проверка выполнена успешно.
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                    example: true
        '400':
          description: Неверные данные запроса.

  /v1/wallet/topup:
    post:
      summary: Top up wallet
      description: Пополняет кошелек на указанную сумму.
      operationId: TopUpWallet
      tags:
        - Wallet
      security:
        - DigestAuth: []
      parameters:
        - name: X-UserId
          in: header
          required: true
          description: ID партнера.
          schema:
            type: string
      requestBody:
        description: Параметры пополнения.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  example: "user_account_12345"
                amount:
                  type: number
                  format: float
                  example: 500.0
      responses:
        '200':
          description: Кошелек успешно пополнен.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wallet topped up successfully.
        '400':
          description: Неверные данные запроса или превышен лимит баланса.
        '404':
          description: Кошелек не найден.

  /v1/wallet/summary:
    post:
      summary: Get monthly wallet summary
      description: Возвращает статистику операций за текущий месяц.
      operationId: GetMonthlySummary
      tags:
        - Wallet
      security:
        - DigestAuth: []
      parameters:
        - name: X-UserId
          in: header
          required: true
          description: ID партнера.
          schema:
            type: string
      responses:
        '200':
          description: Статистика успешно получена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMonthlySummaryOut"
        '400':
          description: Неверные данные запроса.

components:
  securitySchemes:
    DigestAuth:
      type: apiKey
      in: header
      name: X-Digest

  schemas:
    GetMonthlySummaryOut:
      type: object
      properties:
        total_transactions:
          type: integer
          description: Общее количество операций за месяц.
          example: 23
        total_amount:
          type: number
          format: float
          description: Общая сумма операций за месяц.
          example: 42000.00
